Update jfrog.yaml

diff --git a/.github/workflows/jfrog.yaml b/.github/workflows/jfrog.yaml
--- a/.github/workflows/jfrog.yaml
+++ b/.github/workflows/jfrog.yaml
@@ -52,7 +52,11 @@ jobs:
 
       - name: Authenticate JFrog CLI
         run: |
-         echo ${{ secrets.ARTIFACTORY_PASSWORD }} | jfrog config add my-artifactory-12 --artifactory-url https://trial2t885z.jfrog.io/artifactory --access-token - --interactive=false
+          jfrog config add my-artifactory-11 --artifactory-url https://trial2t885z.jfrog.io/artifactory --access-token "${{ secrets.ARTIFACTORY_PASSWORD }}" --interactive=false
+          echo "Checking JFrog connection..."
+          jfrog rt ping || echo "JFrog connection failed"
+          echo "Verifying token..."
+          jfrog config show my-artifactory-11
 
       - name: Push Build Artifacts to Artifactory
         run: |
