Update jfrog.yaml

diff --git a/.github/workflows/jfrog.yaml b/.github/workflows/jfrog.yaml
--- a/.github/workflows/jfrog.yaml
+++ b/.github/workflows/jfrog.yaml
@@ -65,8 +65,13 @@ jobs:
 
       - name: Authenticate JFrog CLI
         run: |
-         jfrog config add my-artifactory-8 --artifactory-url https://trial2t885z.jfrog.io/artifactory --access-token ${{ secrets.ARTIFACTORY_PASSWORD }} --interactive=false
+          jfrog config add my-artifactory-9 --artifactory-url https://trial2t885z.jfrog.io/artifactory --access-token ${{ secrets.ARTIFACTORY_PASSWORD }} --interactive=false
+          echo "Checking JFrog connection..."
+          jfrog rt ping || echo "JFrog connection failed"
+          echo "Verifying token..."
+          jfrog config show my-artifactory-9
 
       - name: Push Build Artifacts to Artifactory
         run: |
           jfrog rt u "artifacts/*" "dotnet-nuget/${{ github.sha }}/" --flat=false --build-name="dotnet-build" --build-number="${{ github.run_number }}"
+          echo "JFrog Upload Exit Code: $?"
